services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-app
    restart: always
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/backend
      - /backend/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-app
    restart: always
    ports:
      - "7000:80"
    volumes:
      - ./frontend/public:/usr/share/nginx/html
    depends_on:
      - backend